plugins {
    id("java")
    id("idea")
    id("eclipse")
    id("maven-publish")
    id("net.minecraftforge.gradle") version "[7.0.9,8.0)"
    id("net.minecraftforge.renamer") version "1.0.2"
}

val minecraft_version: String by project
val minecraft_version_range: String by project
val forge_version: String by project
val forge_version_range: String by project
val loader_version_range: String by project
val geckolib_version: String by project
val geckolib_version_range: String by project
val mclib_version: String by project
val appleskin_version: String by project
val mapping_channel: String by project
val mapping_version: String by project

val mod_id: String by project
val mod_name: String by project
val mod_license: String by project
val mod_version: String by project
val mod_group_id: String by project
val mod_authors: String by project
val mod_description: String by project
val mod_credits: String by project

version = mod_version
group = mod_group_id
base.archivesName = mod_id

// Mojang ships Java 21 to end users in 1.20.5+, so your mod should target Java 21.
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println("Java: ${providers.systemProperty("java.version").get()}, " +
        "JVM: ${providers.systemProperty("java.vm.version").get()} (${providers.systemProperty("java.vendor").get()}), " +
        "Arch: ${providers.systemProperty("os.arch").get()}")

minecraft {
    mappings(mapping_channel, mapping_version)

    useDefaultAccessTransformer()

    runs {
        configureEach {
            workingDir.convention(layout.projectDirectory.dir("run"))

            systemProperty("forge.logging.markers", "REGISTRIES")

            systemProperty("forge.logging.console.level", "debug")

            systemProperty("eventbus.api.strictRuntimeChecks", "true")

            //args("-mixin.config=${mod_id}.mixins.json")
        }

        register("client") {
            systemProperty("forge.enabledGameTestNamespaces", mod_id)
        }

        register("server") {
            systemProperty("forge.enabledGameTestNamespaces", mod_id)
            args("--nogui")
        }

        register("gameTestServer") {
            systemProperty("forge.enabledGameTestNamespaces", mod_id)
        }

        register("data") {
            workingDir = layout.projectDirectory.dir("run-data")

            args("--mod", mod_id, "--all", "--output", layout.projectDirectory.dir("src/generated/resources"), "--existing", layout.projectDirectory.dir("src/main/resources"))
        }
    }
}

// Include resources generated by data generators.
sourceSets.named("main") {
    resources { srcDir(layout.projectDirectory.dir("src/generated/resources")) }
}

repositories {
    minecraft.mavenizer(this)
    maven(fg.forgeMaven)
    maven(fg.minecraftLibsMaven)
    exclusiveContent {
        forRepository {
            maven {
                name = "Sponge"
                url = uri("https://repo.spongepowered.org/repository/maven-public")
            }
        }
        filter {
            includeGroupAndSubgroups("org.spongepowered")
        }
    }
    mavenCentral()
    mavenLocal()

    maven {
        name = "GeckoLib"
        url = uri("https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/")
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }
    maven { url = uri("https://maven.terraformersmc.com/releases/")}
    maven { url = uri("https://maven.ryanliptak.com/") }
    maven { url = uri("https://maven.shedaniel.me/") }

    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    // NOTE: Support for local dependencies is still experimental in ForgeGradle 7.
    //flatDir {
    //    dir "libs"
    //}
}

dependencies {
    // Specify the version of Minecraft to use.
    // Any artifact can be supplied so long as it has a "userdev" classifier artifact and is a compatible patcher artifact.
    // The "userdev" classifier will be requested and setup by ForgeGradle.
    // If the group id is "net.minecraft" and the artifact id is one of ["client", "server", "joined"],
    // then special handling is done to allow a setup of a vanilla dependency without the use of an external repository.
    implementation(minecraft.dependency("net.minecraftforge:forge:$minecraft_version-$forge_version"))

    implementation("software.bernie.geckolib:geckolib-forge-$minecraft_version:$geckolib_version")
    implementation("com.eliotlash.mclib:mclib:$mclib_version")
    runtimeOnly("squeek.appleskin:appleskin-forge:$appleskin_version") {
        exclude("modmenu")
    }

    // Example mod dependency with JEI
    // The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
    //compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
    //compileOnly "mezz.jei:jei-${mc_version}-forge-api:${jei_version}"
    //runtimeOnly "mezz.jei:jei-${mc_version}-forge:${jei_version}"

    // Example mod dependency using a mod jar from ./libs with a flat dir repository
    // This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
    // The group id is ignored when searching -- in this case, it is "blank"
    // NOTE: Support for deobfuscated dependencies has not yet been added in ForgeGradle 7.
    //implementation "blank:coolmod-${mc_version}:${coolmod_version}"

    // For more info:
    // http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
    // http://www.gradle.org/docs/current/userguide/dependency_management.html
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
tasks.named<ProcessResources>("processResources") {
    var replaceProperties = mapOf(
            "minecraft_version" to minecraft_version, "minecraft_version_range" to minecraft_version_range,
            "forge_version" to forge_version, "forge_version_range" to forge_version_range,
            "loader_version_range" to loader_version_range, "geckolib_version" to geckolib_version,
            "geckolib_version_range" to geckolib_version_range,
            "mod_id" to mod_id, "mod_name" to mod_name, "mod_license" to mod_license, "mod_version" to mod_version,
            "mod_authors" to mod_authors, "mod_description" to mod_description, "mod_credits" to mod_credits,
    )
    inputs.property("replaceProperties", replaceProperties)

    filesMatching(listOf("META-INF/mods.toml", "pack.mcmeta")) {
        expand(replaceProperties)
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named<Jar>("jar") {
    manifest {
        attributes(mapOf(
                "Specification-Title"     to mod_id,
                "Specification-Vendor"    to mod_authors,
                "Specification-Version"   to "1", // We are version 1 of ourselves
                "Implementation-Title"    to project.name,
                "Implementation-Version"  to tasks.named<Jar>("jar").get().archiveVersion,
                "Implementation-Vendor"   to mod_authors
        ))
        //attributes["MixinConfigs"] = "${mod_id}.mixins.json"
    }
}

// Creates a task named 'renameJar'
renamer.classes(tasks.named<Jar>("jar")) {
    // You need to point to the mappings you wish to apply, typically this is the Mapped names to SRG for older versions.
    // ForgeGradle/Mavenizer generate these files for the dependencies you declare. So you can use the helper.
    // Or you can specify the file or dependency if you host them yourself.
    map.from(minecraft.dependency.toSrgFile)
    // This is publishable task so you can specify things such as the classifier
    archiveClassifier = "srg"
}

// If you want to create another task, or customize the name you can specify it as the first argument
renamer.classes("renameJarToSrg", tasks.named<Jar>("jar")) {
    // This specifies the map via a dependency coordinate, such as 'net.minecraft:mappings_official:1.20.1-20230612.114412:map2srg@tsrg.gz'
    mappings(minecraft.dependency.toSrg.get())
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
    repositories {
        maven { url = uri(project.layout.projectDirectory.dir("mcmodsrepo").asFile.toString()) }
    }

    publications.register<MavenPublication>("mavenJava") {
        from(components.named("java").get()) // Publish the normal jar
        artifact(tasks.named("renameJar").get())
    }
}

// IntelliJ no longer downloads javadocs and sources by default, this tells Gradle to force IntelliJ to do it.
idea.module {
    setDownloadJavadoc(true)
    setDownloadSources(true)
}

eclipse {
    // Eclipse no longer downloads javadocs and sources by default, this tells Gradle to force Eclipse to do it.
    classpath {
        setDownloadJavadoc(true)
        setDownloadSources(true)
    }

    // NOTE: ForgeGradle 7 does not yet support Eclipse run configurations
    // Run everytime eclipse builds the code
    //autoBuildTasks(genEclipseRuns)
    // Run when importing the project
    //synchronizationTasks("genEclipseRuns")
}

// NOTE: Merging of source sets is now controlled by the property "net.minecraftforge.gradle.merge-source-sets"